### ISSUE TITLE
Discord embedding

### ISSUE THREAD

**Issue by Metacinnabar** [5HT2/srp-go#3]
Embed the image when link pasted into Discord, similar to how https://thispersondoesnotexist.com/image embeds an image.

**Comment by 5HT2** [comment]
I'm closing this as won't fix because Discord caches a websites embed on your device indefinitely (as far as I'm aware), so posting the link would just display the same image each time

**Comment by Metacinnabar** [comment]
Embeds seem to be cached every 5 or 10 minutes or so from my testing.

**Comment by 5HT2** [comment]
That's pretty annoying given srp-go gives a new image on request. The readme already has a todo for adding a Discord embed, I'd rather add text describing the site.
